version: "3.4"

services:
  genotewatcher:
    image: enox/genote-watcher:latest
    ports:
      - "4000:4000"
    environment:
      - GENOTE_USER=
      - GENOTE_PASSWORD=
      - DISCORD_WEBHOOK=
      - TIME_INTERVAL=
